#!/bin/bash

dete=$1
zad=$2
#tests=$3

g++ -std=c++11 -O2 ./solutions/$dete/$zad.cpp -o ./solutions/$dete/$zad

res=0
cntTests=0

echo $zad

tempfile=$(mktemp)

#for i in $(seq -w 01 $tests)
for i in $zad/tests/*.in
do
	fname=$(basename $i .in)
	inf=$fname.in
	outf=$fname.sol

	./solutions/$dete/$zad < ./$zad/tests/$inf > tempfile
        diff -q -Z tempfile ./$zad/tests/$outf > /dev/null
	#echo $?
	#cat ./solutions/$dete/$zad.$i.out
	#echo
	#cat ./$zad/tests/$zad.$i.sol	
	if (( $? == 0 ))
	then
		res=$((res+1))
		echo Test $fname: OK
	else
		echo Test $fname: WA
	fi
	cntTests=$((cntTests+1))
done

rm $tempfile

echo RESULT: $res/$cntTests

echo

